"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { authedFetch } from "@/app/lib/authed-fetch";
import type { buildAdminPortfolio } from "@/lib/admin-portfolio";
type Payload = { items: ReturnType<typeof buildAdminPortfolio>; partial: boolean; generatedAt: string; coverage: Array<{ source: string; available: boolean; truncated: boolean }> };
export default function PortfolioPage() {
  const [data, setData] = useState<Payload | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [onlyPending, setOnlyPending] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); try { const response = await authedFetch("/api/admin/portfolio", { signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha na consulta."); if (!signal?.aborted) setData(payload); } catch (err) { if (!signal?.aborted) setError(err instanceof Error ? err.message : "Falha na consulta."); } finally { if (!signal?.aborted) setLoading(false); } }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const items = data?.items.filter(row => row.name.toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR")) && (!onlyPending || row.issues.length)) || [];
  const pending = data?.items.filter(row => row.issues.length).length ?? 0;
  const critical = data?.items.filter(row => row.priority >= 3).length ?? 0;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Operação da carteira</h1><p className="mt-1 text-sm text-slate-500">Acompanhe suas empresas e resolva as prioridades do dia.</p></div><button className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-50" disabled={loading} onClick={() => void load()}>{loading ? "Atualizando..." : "Atualizar"}</button></header>
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}{data && " Exibindo a última consulta bem-sucedida."}</p>}
    {data?.partial && <p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Cobertura parcial: {data.coverage.filter(row => !row.available || row.truncated).map(row => `${row.source}: ${row.available ? "limite de 500 registros" : "indisponível"}`).join(", ")}. Pendências abrangem os registros carregados.</p>}
    {data && <div className="flex flex-wrap items-center gap-6 text-sm"><span><strong className="text-slate-900">{data.items.length}</strong> empresas</span><span><strong className="text-amber-700">{pending}</strong> precisam de ação</span><span><strong className="text-red-700">{critical}</strong> com prioridade alta</span><Link className="ml-auto font-medium text-indigo-600" href="/admin/clientes">Gerenciar empresas →</Link></div>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div className="flex gap-1 rounded-lg bg-slate-100 p-1">{([[false, "Todas"], [true, "Precisa de ação"]] as const).map(([pendingOnly, label]) => <button key={String(label)} aria-pressed={onlyPending === pendingOnly} onClick={() => setOnlyPending(Boolean(pendingOnly))} className={`rounded-md px-3 py-1.5 text-sm font-medium ${onlyPending === pendingOnly ? "bg-white text-slate-900 shadow-sm" : "text-slate-500"}`}>{label}</button>)}</div><input aria-label="Buscar empresa" placeholder="Buscar empresa" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm sm:w-64" value={search} onChange={event => setSearch(event.target.value)} /></div>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3 font-medium">Empresa</th><th className="px-5 py-3 font-medium">Operação</th><th className="px-5 py-3 font-medium">Próxima ação</th><th className="px-5 py-3 font-medium"><span className="sr-only">Abrir empresa</span></th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(row => <tr key={row.id} className="hover:bg-slate-50/70"><td className="min-w-48 px-5 py-5"><Link href={row.href} className="font-semibold hover:text-indigo-600">{row.name}</Link><p className="mt-1 text-xs text-slate-500">{row.status === "active" ? "Ativo" : row.status}</p></td><td className="px-5 py-5 text-xs text-slate-500"><p>{row.channelCount} canais · {row.projectCount} projetos</p><details className="mt-1"><summary className="cursor-pointer">Custo da IA</summary><p className="mt-1">Estimativa do mês: {row.estimatedAiCostUsd === null ? "sem cobertura" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "USD" }).format(row.estimatedAiCostUsd)}</p></details></td><td className="min-w-64 px-5 py-5">{row.issues[0] ? <><Link href={row.issues[0].href} className={`font-medium ${row.priority >= 3 ? "text-red-700" : row.priority === 2 ? "text-amber-700" : "text-indigo-600"}`}>{row.issues[0].label} →</Link>{row.issues.length > 1 && <details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer">+{row.issues.length - 1} pendências</summary><ul className="mt-2 space-y-2">{row.issues.slice(1).map(issue => <li key={issue.code}><Link href={issue.href} className="hover:text-indigo-600">{issue.label} →</Link></li>)}</ul></details>}</> : <p className="text-xs text-slate-500">Sem pendências nos registros consultados</p>}</td><td className="px-5 py-5"><Link href={row.href} aria-label={`Abrir ${row.name}`} className="font-medium text-indigo-600">Abrir</Link></td></tr>)}</tbody></table></div>
      {!items.length && <p className="p-10 text-center text-sm text-slate-500">{loading ? "Carregando carteira..." : data ? "Nenhuma empresa para estes filtros." : "Consulta indisponível."}</p>}
    </section>
    {data && <p className="text-xs text-slate-400">Atualizado em {new Date(data.generatedAt).toLocaleString("pt-BR")}. O estado dos canais reflete os registros salvos.</p>}
  </div>;
}
