"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, Cpu, KeyRound, Loader2, Plus, Sparkles } from "lucide-react";
import { authedFetch } from "@/app/lib/authed-fetch";

type Tier = "free" | "local" | "cheap" | "premium" | "internal";
type Provider = { id?: string; slug: string; name: string; kind: string; tier: Tier; capabilities: string[]; notes?: string; source?: string; status?: string };
type Payload = { catalog: Provider[]; custom: Provider[]; error?: string };

const TIER_LABELS: Record<Tier, string> = { free: "Grátis / quota", local: "Local", cheap: "Baixo custo", premium: "Premium", internal: "Infra Altum" };
const ALL_CAPABILITIES = ["GENERATE_TEXT", "ANALYZE_RESULTS", "READ_DOCUMENTS", "WEB_RESEARCH", "BROWSER_ASSISTED", "CRM_READ", "CRM_WRITE", "EXTERNAL_MESSAGING", "GENERATE_IMAGE", "GENERATE_VIDEO", "GENERATE_AVATAR_VIDEO", "GENERATE_AUDIO", "TRANSCRIBE_AUDIO", "GENERATE_CREATIVE", "BUILD_PRODUCT", "DEPLOY_SITE", "PUBLISH_CONTENT", "PUBLISH_OR_ADS_WRITE", "READ_ANALYTICS", "RUN_CODE"];

function capabilityLabel(value: string) { return value.toLowerCase().replaceAll("_", " "); }

export default function ToolHubPage() {
  const [data, setData] = useState<Payload>({ catalog: [], custom: [] });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", slug: "", kind: "api", tier: "free" as Tier, capabilities: ["GENERATE_TEXT"], notes: "" });
  const load = useCallback(async () => { try { setLoading(true); setError(""); const response = await authedFetch("/api/admin/agent-os/tool-providers"); const payload = await response.json().catch(() => ({})) as Payload; if (!response.ok) throw new Error(payload.error || "Não foi possível carregar o Tool Hub."); setData(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o Tool Hub."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const providers = useMemo(() => [...data.catalog, ...data.custom], [data]);
  async function createProvider(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { setSaving(true); setError(""); const response = await authedFetch("/api/admin/agent-os/tool-providers", { method: "POST", body: JSON.stringify(form) }); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(payload.error || "Não foi possível registrar o provider."); setOpen(false); setForm({ name: "", slug: "", kind: "api", tier: "free", capabilities: ["GENERATE_TEXT"], notes: "" }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível registrar o provider."); } finally { setSaving(false); } }
  const toggleCapability = (capability: string) => setForm((current) => ({ ...current, capabilities: current.capabilities.includes(capability) ? current.capabilities.filter((value) => value !== capability) : [...current.capabilities, capability] }));
  return <div className="mx-auto max-w-[1440px] space-y-6 pb-10"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-600">Altum Agent OS</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Tool Hub</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">O catálogo de tudo que os agentes podem fazer. Providers só aparecem aqui; conexões e credenciais serão configuradas em uma camada segura separada.</p></div><button onClick={() => setOpen((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500"><Plus size={17} />Catalogar ferramenta</button></header>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {open && <form onSubmit={createProvider} className="rounded-2xl border border-violet-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-2"><Boxes className="text-violet-600" size={18} /><div><h2 className="font-semibold">Adicionar ao catálogo</h2><p className="text-sm text-slate-500">Isto não salva token, nem autoriza um agente. Apenas registra uma capacidade disponível para futura conexão.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="field" placeholder="Ex.: Provider de vídeo" /></Field><Field label="Identificador"><input required value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/\s+/g, "-") })} className="field" placeholder="provider-video" /></Field><Field label="Tipo"><input required value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })} className="field" placeholder="api, modelo, ferramenta..." /></Field><Field label="Custo esperado"><select value={form.tier} onChange={(e) => setForm({ ...form, tier: e.target.value as Tier })} className="field">{Object.entries(TIER_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div><Field label="Observações"><input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="field" placeholder="Uso previsto, limite conhecido ou observação operacional" /></Field><fieldset className="mt-4"><legend className="text-sm font-medium text-slate-700">Capacidades</legend><div className="mt-2 flex flex-wrap gap-2">{ALL_CAPABILITIES.map((capability) => <label key={capability} className={`cursor-pointer rounded-lg border px-2.5 py-1.5 text-xs font-medium ${form.capabilities.includes(capability) ? "border-violet-300 bg-violet-50 text-violet-800" : "border-slate-200 bg-white text-slate-500"}`}><input className="sr-only" type="checkbox" checked={form.capabilities.includes(capability)} onChange={() => toggleCapability(capability)} />{capabilityLabel(capability)}</label>)}</div></fieldset><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-xl px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Cancelar</button><button disabled={saving || !form.capabilities.length} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving && <Loader2 className="animate-spin" size={16} />}{saving ? "Salvando..." : "Adicionar ao catálogo"}</button></div></form>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Boxes} value={String(providers.length)} label="Providers catalogados" tone="violet" /><Stat icon={Cpu} value={String(providers.filter((provider) => ["free", "local"].includes(provider.tier)).length)} label="Opções grátis ou locais" tone="emerald" /><Stat icon={Sparkles} value={String(new Set(providers.flatMap((provider) => provider.capabilities)).size)} label="Capacidades mapeadas" tone="blue" /><Stat icon={KeyRound} value="0" label="Credenciais cadastradas" tone="amber" /></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Catálogo de capacidades</h2><p className="mt-0.5 text-sm text-slate-500">Conexões, tokens, OAuth, escopos e health checks entram na próxima entrega do Tool Hub.</p></div>{loading ? <div className="flex justify-center p-12"><Loader2 className="animate-spin text-violet-600" /></div> : <div className="grid gap-px bg-slate-100 sm:grid-cols-2 xl:grid-cols-3">{providers.map((provider) => <article key={`${provider.source || "builtin"}_${provider.slug}`} className="bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{provider.name}</h3><p className="mt-0.5 text-xs text-slate-500">{provider.kind} · {provider.source === "custom" ? "catálogo personalizado" : "base recomendada"}</p></div><TierBadge tier={provider.tier} /></div><div className="mt-4 flex flex-wrap gap-1.5">{provider.capabilities.slice(0, 5).map((capability) => <span key={capability} className="rounded-md bg-slate-100 px-2 py-1 text-[11px] font-medium text-slate-600">{capabilityLabel(capability)}</span>)}{provider.capabilities.length > 5 && <span className="rounded-md bg-slate-100 px-2 py-1 text-[11px] font-medium text-slate-600">+{provider.capabilities.length - 5}</span>}</div>{provider.notes && <p className="mt-3 text-xs text-slate-500">{provider.notes}</p>}</article>)}</div>}</section><style jsx>{`.field { width: 100%; margin-top: .35rem; border: 1px solid rgb(226 232 240); border-radius: .75rem; background: rgb(248 250 252); padding: .6rem .75rem; font-size: .875rem; outline: none; } .field:focus { border-color: rgb(139 92 246); box-shadow: 0 0 0 3px rgb(237 233 254); }`}</style></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
function TierBadge({ tier }: { tier: Tier }) { const tone: Record<Tier, string> = { free: "bg-emerald-100 text-emerald-800", local: "bg-blue-100 text-blue-800", cheap: "bg-amber-100 text-amber-800", premium: "bg-violet-100 text-violet-800", internal: "bg-slate-100 text-slate-700" }; return <span className={`whitespace-nowrap rounded-full px-2 py-1 text-xs font-medium ${tone[tier]}`}>{TIER_LABELS[tier]}</span>; }
function Stat({ icon: Icon, value, label, tone }: { icon: typeof Boxes; value: string; label: string; tone: "violet" | "emerald" | "blue" | "amber" }) { const colors = { violet: "bg-violet-50 text-violet-600", emerald: "bg-emerald-50 text-emerald-600", blue: "bg-blue-50 text-blue-600", amber: "bg-amber-50 text-amber-600" }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`inline-flex rounded-xl p-2 ${colors[tone]}`}><Icon size={18} /></div><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-0.5 text-sm text-slate-500">{label}</p></div>; }
