"use client";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { authedFetch } from "@/app/lib/authed-fetch";
import { strictAdminScopes } from "@/lib/admin-mcp";
import { scopes } from "@/lib/mcp/contracts";
export default function AdminAuthorizePage() { return <Suspense fallback={<p>Carregando autorização…</p>}><Consent /></Suspense>; }
function Consent() {
  const params = useSearchParams();
  const [selectedScopes, setSelectedScopes] = useState<string[]>([...scopes]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  let requested: ReturnType<typeof strictAdminScopes> | null = null; try { requested = strictAdminScopes(params.get("scope")); } catch { /* Invalid requests remain disabled. */ }
  const requestedScopeKey = params.get("scope") || "";
  // The platform owner chose a full Altum connection. ChatGPT may initially
  // request only the tools it already knows, but future Altum capabilities
  // must not require another OAuth screen. Each cost or external action still
  // requires its own confirmation at execution time.
  useEffect(() => { if (requested) setSelectedScopes([...scopes]); }, [requestedScopeKey]);
  async function authorize() { setBusy(true); setError(""); try { const response = await authedFetch("/api/admin/mcp/authorize", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(params), scopes: selectedScopes }) }); const payload = await response.json(); if (!response.ok || typeof payload.redirect !== "string") throw new Error(payload.error || "Falha na autorização."); window.location.assign(payload.redirect); } catch (err) { setError(err instanceof Error ? err.message : "Falha na autorização."); setBusy(false); } }
  const labels: Record<string, string> = { "context:read": "Empresas, contexto e trabalhos", "crm:read": "Clientes, oportunidades e funil", "crm:write": "Preparar alterações no CRM", "inbox:read": "Conversas e mensagens", "inbox:write": "Preparar respostas e contatos", "reports:read": "Relatórios e resultados", "integrations:read": "Conexões, modelos e saúde", "integrations:write": "Configurar conexões e canais", "events:read": "Histórico e auditoria", "marketing:read": "Campanhas, mídia e estratégias", "marketing:draft": "Criar planos e rascunhos de campanha", "automation:write": "Criar automações supervisionadas", "knowledge:write": "Base de conhecimento e produtos", "calendar:write": "Agenda, tarefas e compromissos", "settings:write": "Equipe e configurações operacionais", "ai:draft": "Missões, agentes, imagens, vídeos e avatares" };
  const allSelected = selectedScopes.length === scopes.length;
  return <main className="min-h-screen bg-[#171717] px-4 py-10 text-zinc-100"><section className="mx-auto max-w-2xl space-y-6 rounded-3xl border border-white/10 bg-[#212121] p-6 shadow-2xl sm:p-9"><div className="space-y-2"><p className="text-xs font-medium uppercase tracking-[0.18em] text-violet-300">Conexão segura</p><h1 className="text-2xl font-semibold tracking-tight">Dar acesso completo da Altum ao ChatGPT?</h1><p className="max-w-xl text-sm leading-6 text-zinc-400">O ChatGPT poderá usar as capacidades autorizadas da Altum: operação, mídia, missões, agentes, campanhas, documentos e resultados. Chaves, segredos e credenciais nunca são expostos. Gastos, publicação, mensagens e ações externas continuam exigindo confirmação no momento certo.</p></div>{error && <p role="alert" className="rounded-xl border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-100">{error}</p>}{!requested && <p role="alert" className="text-sm text-red-300">Não foi possível validar este pedido. Volte ao ChatGPT e tente conectar novamente.</p>}<fieldset disabled={busy} className="space-y-3"><div className="flex items-center justify-between gap-3"><legend className="font-medium">Capacidades da Altum</legend><button type="button" onClick={() => setSelectedScopes(allSelected ? ["context:read"] : [...scopes])} className="text-xs font-semibold text-violet-300 hover:text-violet-200">{allSelected ? "Manter apenas o essencial" : "Selecionar acesso completo"}</button></div><p className="text-sm text-zinc-400">Acesso completo já vem selecionado. Você pode reduzir apenas se quiser limitar o ChatGPT.</p><div className="space-y-2">{scopes.map(scope => <label key={scope} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-3 text-sm"><input className="size-4 accent-violet-500" type="checkbox" disabled={scope === "context:read"} checked={selectedScopes.includes(scope)} onChange={() => setSelectedScopes(current => current.includes(scope) ? current.filter(value => value !== scope) : [...current, scope])} />{labels[scope]}</label>)}</div></fieldset>{requested?.offline && <p className="text-xs leading-5 text-zinc-500">A conexão pode ser renovada por até sessenta dias e poderá ser removida nas configurações da Altum.</p>}<div className="flex flex-wrap items-center gap-3 pt-1"><button className="rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-400 disabled:cursor-not-allowed disabled:opacity-40" disabled={busy || !requested} onClick={() => void authorize()}>{busy ? "Conectando…" : "Permitir acesso completo e voltar ao ChatGPT"}</button><Link href="/admin/mcp" className="px-2 py-2 text-sm text-zinc-400 hover:text-white">Cancelar</Link></div></section></main>;
}
