"use client";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { authedFetch } from "@/app/lib/authed-fetch";
import { strictAdminScopes } from "@/lib/admin-mcp";
export default function AdminAuthorizePage() { return <Suspense fallback={<p>Carregando autorização…</p>}><Consent /></Suspense>; }
function Consent() {
  const params = useSearchParams(); const [companies, setCompanies] = useState<Array<{ id: string; name: string }>>([]);
  const [tenantIds, setTenantIds] = useState<string[]>([]), [selectedScopes, setSelectedScopes] = useState<string[]>(["context:read"]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  let requested: ReturnType<typeof strictAdminScopes> | null = null; try { requested = strictAdminScopes(params.get("scope")); } catch { /* Invalid requests remain disabled. */ }
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const response = await authedFetch("/api/admin/marketing/overview", { signal: controller.signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha ao carregar empresas."); if (!controller.signal.aborted) { setCompanies(payload.companies || []); if (payload.partial) setError("A lista de empresas está parcial. Escolha vínculos confirmados."); } } catch (err) { if (!controller.signal.aborted) setError(err instanceof Error ? err.message : "Falha na consulta."); } })(); return () => controller.abort(); }, []);
  async function authorize() { setBusy(true); setError(""); try { const response = await authedFetch("/api/admin/mcp/authorize", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(params), tenantIds, scopes: selectedScopes }) }); const payload = await response.json(); if (!response.ok || typeof payload.redirect !== "string") throw new Error(payload.error || "Falha na autorização."); window.location.assign(payload.redirect); } catch (err) { setError(err instanceof Error ? err.message : "Falha na autorização."); setBusy(false); } }
  const labels: Record<string, string> = { "context:read": "Perfil das empresas", "crm:read": "Clientes e oportunidades", "inbox:read": "Conversas e mensagens", "reports:read": "Relatórios", "integrations:read": "Estado das integrações", "events:read": "Auditoria operacional", "marketing:read": "Campanhas, rastreamento e estratégias", "marketing:draft": "Criar recomendações de campanhas", "ai:draft": "Propor ajustes do assistente" };
  return <div className="mx-auto max-w-3xl space-y-5 rounded-xl border bg-white p-6 text-slate-900"><h1 className="text-2xl font-bold">Autorizar ChatGPT na operação Altum</h1><p className="text-sm text-slate-500">Escolha as empresas e os dados acessíveis. As propostas do ChatGPT exigem revisão na Altum.</p><p className="break-all text-xs text-slate-500">Cliente: {params.get("client_id")}<br />Retorno: {params.get("redirect_uri")}</p>{error && <p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{error}</p>}{!requested && <p role="alert" className="text-red-700">Solicitação inválida. Inicie a conexão novamente no ChatGPT.</p>}<fieldset disabled={busy}><legend className="mb-3 font-semibold">Empresas ({tenantIds.length}/20)</legend><div className="max-h-72 space-y-2 overflow-auto">{companies.map(row => <label className="flex items-center gap-2 text-sm" key={row.id}><input type="checkbox" checked={tenantIds.includes(row.id)} disabled={!tenantIds.includes(row.id) && tenantIds.length >= 20} onChange={() => setTenantIds(current => current.includes(row.id) ? current.filter(id => id !== row.id) : [...current, row.id])} />{row.name}</label>)}</div></fieldset><fieldset disabled={busy}><legend className="mb-3 font-semibold">Permissões</legend><div className="space-y-2">{requested?.scopes.map(scope => <label key={scope} className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={scope === "context:read"} checked={selectedScopes.includes(scope)} onChange={() => setSelectedScopes(current => current.includes(scope) ? current.filter(value => value !== scope) : [...current, scope])} />{labels[scope]}</label>)}</div></fieldset>{requested?.offline && <p className="text-xs text-slate-500">A conexão poderá ser renovada por até sessenta dias. Você pode revogá-la no admin.</p>}<div className="flex gap-3"><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" disabled={busy || !requested || !tenantIds.length} onClick={() => void authorize()}>{busy ? "Autorizando…" : "Autorizar empresas selecionadas"}</button><Link href="/admin/mcp" className="px-4 py-2 text-sm text-slate-500">Cancelar</Link></div></div>;
}
