import { persistOperatorReport } from "@/lib/server/growth/operator-storage";
import { FieldValue } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { adminDb } from "@/app/lib/server/firebase-admin";
import { requireRequestUser, RouteAuthError } from "@/app/lib/server/route-auth";
import { decryptSecret } from "@/app/lib/server/secret-crypto";
import { fetchAdportMetaOperatorReport } from "@/lib/server/growth/adport-connectors";
import { assertTenantAccess, assertTenantCapability, TenantAccessError } from "@/lib/server/tenant";
import { assertTenantModule } from "@/lib/server/tenant-entitlements";

const clean = (value: unknown, max = 180) => typeof value === "string" ? value.trim().slice(0, max) : "";
type ChannelRow = Record<string, unknown> & { id: string };
const iso = (value: unknown) => (value as { toDate?: () => Date } | null)?.toDate?.().toISOString?.() || null;
const fail = (error: unknown) => { if (error instanceof RouteAuthError) return NextResponse.json({ error: error.message, code: error.code }, { status: error.status }); if (error instanceof TenantAccessError) return NextResponse.json({ error: error.message, code: error.code }, { status: 403 }); console.error("Falha no operador Meta Ads:", error); return NextResponse.json({ error: "Nao foi possivel atualizar o Meta Ads. Confira a conexao." }, { status: 500 }); };

async function channels(tenantId: string) { const snap = await adminDb.collection("tenant_channels").where("tenantId", "==", tenantId).limit(30).get(); return snap.docs.map((doc): ChannelRow => ({ id: doc.id, ...doc.data() })).filter((item) => item.type === "meta_ads"); }
const view = (item: Record<string, unknown> & { id: string }) => ({ id: item.id, name: clean(item.name || item.label) || "Meta Ads", accountId: clean(item.externalAccountId), status: clean(item.status, 30), connectionStatus: clean(item.connectionStatus, 30), ready: item.status === "active" && Boolean(item.externalAccountId && item.accessToken) });

export async function GET(req: Request, context: { params: Promise<{ tenantId: string }> }) { try { const user = await requireRequestUser(req); const { tenantId } = await context.params; const membership = await assertTenantAccess(user.uid, tenantId); await assertTenantModule(tenantId, "marketing"); assertTenantCapability(membership, "view_metrics"); const [items, reports] = await Promise.all([channels(tenantId), adminDb.collection("meta_ads_operator_reports").where("tenantId", "==", tenantId).limit(30).get()]); return NextResponse.json({ ok: true, channels: items.map(view), reports: reports.docs.map((doc) => { const data = doc.data(); return { id: doc.id, channelId: data.channelId, generatedAt: iso(data.generatedAt), report: data.report || null }; }).sort((a, b) => String(b.generatedAt || "").localeCompare(String(a.generatedAt || ""))) }); } catch (error) { return fail(error); } }

export async function POST(req: Request, context: { params: Promise<{ tenantId: string }> }) { try { const user = await requireRequestUser(req); const { tenantId } = await context.params; const membership = await assertTenantAccess(user.uid, tenantId); await assertTenantModule(tenantId, "marketing"); assertTenantCapability(membership, "manage_channels"); const body = await req.json().catch(() => ({})) as Record<string, unknown>; const channelId = clean(body.channelId, 120); const rangeDays = [7, 14, 30].includes(Number(body.rangeDays)) ? Number(body.rangeDays) : 30; const snap = await adminDb.collection("tenant_channels").doc(channelId).get(); const channel: ChannelRow | null = snap.exists ? { id: snap.id, ...snap.data() } : null; if (!channel || channel.tenantId !== tenantId || channel.type !== "meta_ads") return NextResponse.json({ error: "Conta Meta Ads nao encontrada." }, { status: 404 }); const accessToken = clean(decryptSecret(channel.accessToken), 4000); const accountId = clean(channel.externalAccountId); if (channel.status !== "active" || !accessToken || !accountId) return NextResponse.json({ error: "Conexao Meta Ads incompleta." }, { status: 409 }); const metadata = channel.metadata && typeof channel.metadata === "object" && !Array.isArray(channel.metadata) ? channel.metadata as Record<string, unknown> : {}; const to = new Date(); const from = new Date(to.getTime() - (rangeDays - 1) * 86400_000); const report = await fetchAdportMetaOperatorReport({ platform: "meta_ads", accountId, channelId, accessToken, appId: clean(metadata.appId) || undefined, appSecret: clean(metadata.appSecret, 4000) || undefined, actionTypeFilters: Array.isArray(metadata.actionTypeFilters) ? metadata.actionTypeFilters.map(String) : undefined, currency: clean(metadata.currency, 3) || "BRL", from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }); const reportId = `${tenantId}_${channelId}`.replaceAll("/", "_"); await persistOperatorReport(snap, "meta_ads_operator_reports", reportId, { tenantId, channelId, accountId: report.accountId, report, generatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid, source: "adport_meta_marketing_api" }); return NextResponse.json({ ok: true, report, generatedAt: new Date().toISOString() }); } catch (error) { return fail(error); } }
