import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { adminDb } from "@/app/lib/server/firebase-admin";
import { requireRequestUser, RouteAuthError } from "@/app/lib/server/route-auth";

const schema = z.object({
  tenantId: z.string().trim().min(1).max(180), displayName: z.string().trim().min(2).max(100),
  identityType: z.enum(["person", "character"]).default("person"), role: z.enum(["founder", "creator", "sales", "support", "other"]),
  identityAnchor: z.string().trim().max(1800).default(""), visualStyle: z.string().trim().max(500).default(""), voiceDirection: z.string().trim().max(500).default(""), continuity: z.enum(["exploratory", "campaign", "production"]).default("production"),
  allowedUses: z.array(z.enum(["organic_content", "paid_ads", "sales_video", "support_video"])) .min(1), restrictions: z.array(z.string().trim().min(2).max(240)).max(20).default([]),
  likenessConsent: z.boolean().default(false), voiceConsent: z.boolean().default(false), rightsConfirmed: z.boolean().default(false), disclosureRequired: z.boolean().default(true),
}).superRefine((value, context) => {
  if (value.identityType === "person" && !value.likenessConsent) context.addIssue({ code: z.ZodIssueCode.custom, path: ["likenessConsent"], message: "Confirme a autorização de imagem da pessoa." });
  if (value.identityType === "person" && !value.voiceConsent) context.addIssue({ code: z.ZodIssueCode.custom, path: ["voiceConsent"], message: "Confirme a autorização de voz da pessoa." });
  if (value.identityType === "character" && !value.rightsConfirmed) context.addIssue({ code: z.ZodIssueCode.custom, path: ["rightsConfirmed"], message: "Confirme que este personagem é seu ou está autorizado." });
});
function date(value: unknown) { return value && typeof value === "object" && "toDate" in value && typeof (value as { toDate?: unknown }).toDate === "function" ? (value as { toDate: () => Date }).toDate().toISOString() : null; }
function fail(error: unknown) { if (error instanceof RouteAuthError) return Response.json({ error: error.message }, { status: error.status }); console.error("Falha no Avatar Studio:", error); return Response.json({ error: "Não foi possível salvar o perfil de avatar." }, { status: 500 }); }
export async function GET(request: Request) { try { await requireRequestUser(request, { roles: ["agency_admin"] }); const [avatars, tenants, jobs, approvals] = await Promise.all([adminDb.collection("avatar_profiles").limit(200).get(), adminDb.collection("tenants").orderBy("__name__").limit(200).get(), adminDb.collection("avatar_jobs").limit(300).get(), adminDb.collection("agent_approvals").limit(300).get()]); const approvalByJob = new Map(approvals.docs.map((doc) => { const row = doc.data(); return [String(row.avatarJobId || ""), { id: doc.id, status: String(row.status || "pending"), title: String(row.title || "Autorização de avatar"), summary: String(row.summary || "") }]; })); const anchorByAvatar = new Map<string, { id: string; status: string; approval: { id: string; status: string; title: string; summary: string } | null }>(); for (const job of jobs.docs) { const row = job.data(); if (row.stage !== "anchor" || typeof row.avatarId !== "string") continue; const existing = anchorByAvatar.get(row.avatarId); const candidate = { id: job.id, status: String(row.status || "pending_approval"), approval: approvalByJob.get(job.id) || null }; if (!existing || ["pending_approval", "approved_for_anchor", "running"].includes(candidate.status)) anchorByAvatar.set(row.avatarId, candidate); } return Response.json({ items: avatars.docs.map((doc) => { const row = doc.data(); return { id: doc.id, tenantId: String(row.tenantId || ""), displayName: String(row.displayName || ""), identityType: row.identityType === "character" ? "character" : "person", identityAnchor: String(row.identityAnchor || ""), visualStyle: String(row.visualStyle || ""), voiceDirection: String(row.voiceDirection || ""), continuity: String(row.continuity || "production"), role: String(row.role || "other"), allowedUses: Array.isArray(row.allowedUses) ? row.allowedUses.map(String) : [], restrictions: Array.isArray(row.restrictions) ? row.restrictions.map(String) : [], likenessConsent: row.likenessConsent === true, voiceConsent: row.voiceConsent === true, disclosureRequired: row.disclosureRequired !== false, status: String(row.status || "draft"), referenceCount: Number(row.referenceCount || 0), anchor: anchorByAvatar.get(doc.id) || null, createdAt: date(row.createdAt) }; }), tenants: tenants.docs.map((doc) => ({ id: doc.id, name: String(doc.get("name") || doc.id) })) }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return fail(error); } }
export async function POST(request: Request) { try { const actor = await requireRequestUser(request, { roles: ["agency_admin"] }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) throw new RouteAuthError(400, "invalid_avatar", "Revise os direitos, a identidade e os usos permitidos do perfil."); const input = parsed.data; if (!(await adminDb.collection("tenants").doc(input.tenantId).get()).exists) throw new RouteAuthError(404, "tenant_missing", "Empresa não encontrada."); const identityAnchor = input.identityAnchor || `Manter a identidade visual aprovada de ${input.displayName}; preservar traços, proporções, estilo e voz das referências privadas.`; const ref = adminDb.collection("avatar_profiles").doc(); const batch = adminDb.batch(); batch.set(ref, { ...input, identityAnchor, status: "reference_required", consentedAt: FieldValue.serverTimestamp(), createdBy: actor.uid, createdByName: actor.name, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); batch.set(adminDb.collection("audit_logs").doc(), { type: "avatar_profile_created", actorId: actor.uid, actorName: actor.name, tenantId: input.tenantId, avatarId: ref.id, identityType: input.identityType, allowedUses: input.allowedUses, createdAt: FieldValue.serverTimestamp() }); await batch.commit(); return Response.json({ ok: true, id: ref.id }, { status: 201 }); } catch (error) { return fail(error); } }
