export type MetaAdsRow = { id: string; name: string; campaignId?: string; campaignName?: string; adSetId?: string; adSetName?: string; status: string; impressions: number; clicks: number; spend: number; leads: number; purchaseValue: number; ctr: number; cpc: number; frequency: number; roas: number };
export type MetaAdsRecommendation = { id: string; severity: "high" | "medium" | "opportunity"; type: "stop_waste" | "scale_winner" | "creative_fatigue"; title: string; detail: string; evidence: string[]; nextAction?: { tool: "draft_campaign_pause" | "draft_campaign_budget_change"; arguments: Record<string, unknown> } };
export type MetaAdsOperatorReport = { accountId: string; channelId: string; currency: string; from: string; to: string; campaigns: MetaAdsRow[]; adSets: MetaAdsRow[]; ads: MetaAdsRow[]; totals: { campaigns: number; impressions: number; clicks: number; spend: number; leads: number; purchaseValue: number; ctr: number; cpc: number; cpl: number; roas: number }; recommendations: MetaAdsRecommendation[]; source: { project: "AdPort"; package: "@adport/provider-meta"; mode: "live_meta_marketing_api" } };
const round = (value: number, decimals = 2) => Number(value.toFixed(decimals));
const money = (value: number, currency: string) => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value);

export function analyzeMetaAdsOperator(input: Omit<MetaAdsOperatorReport, "totals" | "recommendations" | "source">): MetaAdsOperatorReport {
  const total = input.campaigns.reduce((sum, item) => ({ impressions: sum.impressions + item.impressions, clicks: sum.clicks + item.clicks, spend: sum.spend + item.spend, leads: sum.leads + item.leads, purchaseValue: sum.purchaseValue + item.purchaseValue }), { impressions: 0, clicks: 0, spend: 0, leads: 0, purchaseValue: 0 });
  const recommendations: MetaAdsRecommendation[] = [];
  input.campaigns.forEach((item) => {
    if (item.status === "ACTIVE" && item.spend >= 25 && item.leads === 0) recommendations.push({ id: `stop-${item.id}`, severity: "high", type: "stop_waste", title: `Revisar gasto sem lead em ${item.name}`, detail: "A campanha esta ativa, consumiu verba e nao registrou leads na janela.", evidence: [`Gasto: ${money(item.spend, input.currency)}`, `${item.clicks} cliques e nenhum lead`], nextAction: { tool: "draft_campaign_pause", arguments: { platform: "meta_ads", campaignId: item.id, adAccountId: input.accountId, reason: "Campanha ativa consumiu verba sem registrar leads na janela.", evidence: [`Gasto de ${money(item.spend, input.currency)} com ${item.clicks} cliques e nenhum lead.`] } } });
  });
  input.ads.filter((item) => item.spend >= 10 && (item.frequency >= 3.5 || (item.impressions >= 1000 && item.ctr < 1))).slice(0, 20).forEach((item) => recommendations.push({ id: `creative-${item.id}`, severity: item.frequency >= 4 ? "high" : "medium", type: "creative_fatigue", title: `Revisar criativo ${item.name}`, detail: "O anuncio apresenta frequencia alta ou CTR baixo e pode estar perdendo eficiencia.", evidence: [`Frequencia ${round(item.frequency, 2)}`, `CTR ${round(item.ctr, 2)}%`, `Gasto ${money(item.spend, input.currency)}`] }));
  recommendations.sort((a, b) => ({ high: 0, medium: 1, opportunity: 2 }[a.severity] - ({ high: 0, medium: 1, opportunity: 2 }[b.severity])));
  return { ...input, totals: { campaigns: input.campaigns.length, ...total, spend: round(total.spend), purchaseValue: round(total.purchaseValue), ctr: round(total.impressions ? total.clicks * 100 / total.impressions : 0, 4), cpc: round(total.clicks ? total.spend / total.clicks : 0, 4), cpl: round(total.leads ? total.spend / total.leads : 0, 4), roas: round(total.spend ? total.purchaseValue / total.spend : 0, 4) }, recommendations: recommendations.slice(0, 50), source: { project: "AdPort", package: "@adport/provider-meta", mode: "live_meta_marketing_api" } };
}
