"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import AdminMediaConnections from "@/components/admin/AdminMediaConnections";
import { authedFetch } from "@/app/lib/authed-fetch";
import type { AdminMarketingOverview } from "@/lib/admin-marketing-overview";
import type { AdminBatchRequest } from "@/lib/admin-batch";

type Payload = AdminMarketingOverview & { partial: boolean; generatedAt: string; coverage: Array<{ source: string; available: boolean; truncated: boolean }> };
type BatchResult = { tenantId: string; ok: boolean; status: string; error: string | null };
type History = { id: string; action: string; status: string; total: number; results: BatchResult[] };
const field = "rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm";
const button = "rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40";
const date = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR") : "Sem registro";
const platformName = (value: string) => ({ meta_ads: "Meta Ads", google_ads: "Google Ads" }[value] || value);
const statusName = (value: string) => ({ pending_review: "Aguardando revisão", approved_pending_apply: "Aprovado, aguardando aplicação", applying: "Em execução", applied: "Aplicado", rejected: "Rejeitado", apply_failed_requires_review: "Conferir resultado no provedor" }[value] || value);
function money(value: number | null, currency: string | null) {
  if (value === null) return "Sem dado";
  if (!currency) return `${value.toLocaleString("pt-BR")} (sem moeda)`;
  try { return new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value); }
  catch { return `${value.toLocaleString("pt-BR")} ${currency}`; }
}
export default function AdminMediaPage() {
  const [data, setData] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tenant, setTenant] = useState("");
  const [showConnections, setShowConnections] = useState(false);
  const [connectionTarget, setConnectionTarget] = useState({ tenantId: "", platform: "meta_ads" });
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<"accounts" | "campaigns" | "drafts" | "tracking" | "pixels">("accounts");
  const [selected, setSelected] = useState<string[]>([]);
  const [reason, setReason] = useState("");
  const [percent, setPercent] = useState("10");
  const [rangeDays, setRangeDays] = useState<7 | 14 | 30>(30);
  const [preview, setPreview] = useState<AdminBatchRequest | null>(null);
  const [results, setResults] = useState<BatchResult[]>([]);
  const [history, setHistory] = useState<History[]>([]);
  const [pixel, setPixel] = useState({ tenantId: "", provider: "meta", name: "", externalId: "", domains: "" });
  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true);
    try {
      const response = await authedFetch("/api/admin/marketing/overview", { signal });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Falha ao carregar a central de mídia.");
      if (!signal?.aborted) setData(payload);
    } catch (err) { if (!signal?.aborted) setError(err instanceof Error ? err.message : "Falha na consulta."); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, []);
  const loadHistory = useCallback(async (signal?: AbortSignal) => {
    try { const response = await authedFetch("/api/admin/marketing/batch", { signal }); if (!response.ok) throw new Error("Histórico de lotes indisponível."); const payload = await response.json(); if (!signal?.aborted) setHistory(payload.items || []); }
    catch (err) { if (!signal?.aborted) setError(err instanceof Error ? err.message : "Histórico indisponível."); }
  }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); void loadHistory(controller.signal); return () => controller.abort(); }, [load, loadHistory]);
  useEffect(() => { if (window.location.search) setShowConnections(true); }, []);
  const match = (row: { tenantId: string | null; companyName: string; name?: string; title?: string }) => (!tenant || row.tenantId === tenant) && `${row.companyName} ${row.name || row.title || ""}`.toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR"));
  const accounts = (data?.accounts || []).filter(match), campaigns = (data?.campaigns || []).filter(match), drafts = (data?.drafts || []).filter(match), tracking = (data?.tracking || []).filter(match), pixels = (data?.pixels || []).filter(match);
  const companies = (data?.companies || []).map(company => ({ ...company, name: company.name === company.id ? data?.accounts.find(account => account.tenantId === company.id)?.companyName || company.name : company.name }));
  function toggle(id: string) { setPreview(null); setSelected(current => current.includes(id) ? current.filter(key => key !== id) : [...current, id].slice(0, 20)); }
  function prepare(action: AdminBatchRequest["action"], budget = false) {
    setError(null); setPreview(null);
    let targets: AdminBatchRequest["targets"] = [];
    if (action === "sync" || action === "discover_pixels") targets = accounts.filter(row => selected.includes(row.id) && row.source === "tenant_channels" && row.tenantId).map(row => ({ tenantId: row.tenantId!, platform: row.platform as "meta_ads" | "google_ads", channelId: row.recordId }));
    else if (action === "draft") {
      const rows = campaigns.filter(row => selected.includes(row.id)); const delta = Number(percent);
      if (reason.trim().length < 8) { setError("Explique o motivo da recomendação com pelo menos oito caracteres."); return; }
      if (budget && (!Number.isFinite(delta) || delta === 0 || Math.abs(delta) > 25 || rows.some(row => !row.dailyBudget || !row.currency))) { setError("A verba exige orçamento diário, moeda e variação entre -25% e +25%, diferente de zero. Sincronize os dados que faltam."); return; }
      targets = rows.filter(row => row.tenantId && !row.stale).map(row => ({ tenantId: row.tenantId!, tool: budget ? "draft_campaign_budget_change" : "draft_campaign_pause", arguments: { platform: row.platform as "meta_ads" | "google_ads", campaignId: row.campaignId, adAccountId: row.accountId, reason: reason.trim(), evidence: [`Relatório ${row.from} a ${row.to}; atualizado ${row.generatedAt}; gasto ${row.spend ?? "sem dado"}; ${row.conversionLabel}: ${row.conversions ?? "sem dado"}`], ...(budget ? { currentDailyBudget: row.dailyBudget!, proposedDailyBudget: Number((row.dailyBudget! * (1 + delta / 100)).toFixed(2)), currency: row.currency! } : {}) } }));
    } else {
      const rows = drafts.filter(row => selected.includes(row.id)); const allowed = action === "apply" ? ["approved_pending_apply"] : ["pending_review", "approved_pending_apply"];
      if (rows.some(row => !allowed.includes(row.status) || (action !== "reject" && !row.previewComplete))) { setError("A seleção contém uma recomendação que não permite esta ação."); return; }
      targets = rows.filter(row => row.tenantId).map(row => ({ tenantId: row.tenantId!, draftId: row.id }));
    }
    if (!targets.length || targets.length !== selected.length) { setError("Selecione até 20 registros com vínculo e dados válidos para esta ação."); return; }
    setPreview({ requestKey: crypto.randomUUID(), action, targets, ...(action === "sync" ? { rangeDays } : {}), ...(action === "apply" ? { confirmed: true } : {}) });
  }
  async function execute() {
    if (!preview || busy) return;
    setBusy(true); setError(null); setResults([]);
    try { const response = await authedFetch("/api/admin/marketing/batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(preview) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Lote inconclusivo. Consulte o histórico antes de repetir."); setResults(payload.results || []); setPreview(null); setSelected([]); await load(); await loadHistory(); }
    catch (err) { setError(err instanceof Error ? err.message : "Falha no lote. Confira o histórico antes de repetir."); }
    finally { setBusy(false); }
  }
  async function registerPixel(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError(null);
    try { const response = await authedFetch("/api/admin/marketing/pixels", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...pixel, domains: pixel.domains.split(",").map(value => value.trim()).filter(Boolean) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha no cadastro."); setPixel(current => ({ ...current, name: "", externalId: "", domains: "" })); await load(); }
    catch (err) { setError(err instanceof Error ? err.message : "Falha no cadastro."); } finally { setBusy(false); }
  }
  const checkbox = (id: string, label: string, disabled: boolean) => <input type="checkbox" aria-label={`Selecionar ${label}`} disabled={busy || disabled} checked={selected.includes(id)} onChange={() => toggle(id)} />;
  return <div className="mx-auto max-w-7xl space-y-5 text-slate-900">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Central de mídia</h1><p className="mt-1 text-sm text-slate-500">Operação de campanhas de toda a carteira.</p></div><div className="flex gap-2"><Link href="/admin/estrategias" className={field}>Estratégias e aprendizado</Link><button className={button} disabled={loading || busy} onClick={() => { setError(null); void load(); void loadHistory(); }}>Atualizar visão</button></div></header>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {data && tab === "accounts" && <details id="admin-media-connect" open={showConnections || undefined} onToggle={event => setShowConnections(event.currentTarget.open)} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Conectar ou reconectar uma conta de anúncios</summary><div className="mt-4"><AdminMediaConnections key={`${connectionTarget.tenantId}:${connectionTarget.platform}`} initialTenantId={connectionTarget.tenantId} initialPlatform={connectionTarget.platform} companies={companies} onConnected={() => load()} /></div></details>}
    {data?.partial && <p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Cobertura parcial: {data.coverage.filter(row => !row.available || row.truncated).map(row => `${row.source} (${row.available ? "limite de 500 registros" : "indisponível"})`).join(", ")}. Totais abrangem apenas os registros carregados.</p>}
    {!!results.length && <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Resultado por empresa</h2>{results.map((row, index) => <p key={index} className={`mt-2 text-sm ${row.ok ? "text-emerald-700" : "text-red-700"}`}>{companies.find(company => company.id === row.tenantId)?.name || row.tenantId}: {row.ok ? statusName(row.status) : row.error || "Conferir resultado"}</p>)}</section>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">
      <div className="flex flex-wrap gap-1 border-b p-3" role="tablist">{([["accounts", "Contas"], ["campaigns", "Campanhas"], ["drafts", "Recomendações"], ["tracking", "Rastreamento"], ["pixels", "Pixels"]] as const).map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === key ? "bg-indigo-50 text-indigo-700" : "text-slate-500"}`} disabled={busy} onClick={() => { setTab(key); setSelected([]); setPreview(null); }}>{label}</button>)}</div>
      <div className="flex flex-wrap gap-3 p-4"><input className={`${field} flex-1`} aria-label="Buscar empresa ou campanha" placeholder="Buscar empresa ou campanha" value={search} onChange={event => { setSearch(event.target.value); setSelected([]); setPreview(null); }} /><select className={field} aria-label="Empresa" value={tenant} onChange={event => { setTenant(event.target.value); setSelected([]); setPreview(null); }}><option value="">Todas as empresas</option>{companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div>
      {selected.length > 0 && (tab === "accounts" || tab === "campaigns" || tab === "drafts") && <div className="flex flex-wrap items-center gap-2 border-b px-4 pb-4"><span className="text-sm text-slate-500">{selected.length}/20 selecionados</span>{tab === "accounts" && <><select className={field} aria-label="Período da sincronização" value={rangeDays} onChange={event => { setRangeDays(Number(event.target.value) as 7 | 14 | 30); setPreview(null); }}><option value={7}>7 dias</option><option value={14}>14 dias</option><option value={30}>30 dias</option></select><button className={button} disabled={!selected.length || busy} onClick={() => prepare("sync")}>Sincronizar contas</button><button className={button} disabled={!selected.length || busy} onClick={() => prepare("discover_pixels")}>Consultar pixels e conversões</button></>}{tab === "campaigns" && <><input className={field} value={reason} onChange={event => { setReason(event.target.value); setPreview(null); }} placeholder="Motivo da recomendação" aria-label="Motivo da recomendação" /><button className={button} disabled={!selected.length || busy} onClick={() => prepare("draft")}>Propor pausa</button><input className={`${field} w-24`} type="number" min={-25} max={25} value={percent} onChange={event => { setPercent(event.target.value); setPreview(null); }} aria-label="Variação percentual da verba" /><button className={button} disabled={!selected.length || busy} onClick={() => prepare("draft", true)}>Propor verba (%)</button></>}{tab === "drafts" && <>{(["approve", "reject", "apply"] as const).map(action => <button key={action} className={button} disabled={!selected.length || busy} onClick={() => prepare(action)}>{{ approve: "Aprovar", reject: "Rejeitar", apply: "Aplicar no provedor" }[action]}</button>)}</>}</div>}
      {preview && <div className="m-4 rounded-xl border border-indigo-200 bg-indigo-50 p-4"><h2 className="font-semibold">Revisar lote: {{ sync: "sincronização", discover_pixels: "consulta de pixels e conversões", draft: "recomendações", approve: "aprovação", reject: "rejeição", apply: "aplicação de ações" }[preview.action]}</h2><p className="mt-1 text-sm">{preview.action === "apply" ? "A confirmação executa as mudanças aprovadas nas contas dos provedores." : "Confira as empresas e os alvos antes de confirmar."}</p><ul className="my-3 space-y-2 text-sm">{preview.targets.map((target, index) => { const draft = data?.drafts.find(row => row.id === target.draftId); return <li key={index}>{companies.find(company => company.id === target.tenantId)?.name || target.tenantId} · {target.arguments?.campaignId || draft?.title || target.channelId}{target.arguments?.proposedDailyBudget !== undefined && ` · ${money(target.arguments.currentDailyBudget!, target.arguments.currency!)} → ${money(target.arguments.proposedDailyBudget, target.arguments.currency!)}`}{draft?.change.to !== null && draft?.change.to !== undefined && ` · ${money(draft.change.from, draft.change.currency)} → ${money(draft.change.to, draft.change.currency)}`}{draft && <pre className="mt-1 whitespace-pre-wrap break-all text-xs">{JSON.stringify(draft.details, null, 2)}</pre>}</li>; })}</ul><button className={button} disabled={busy} onClick={() => void execute()}>{busy ? "Executando…" : "Confirmar lote"}</button><button className="ml-3 text-sm" disabled={busy} onClick={() => setPreview(null)}>Cancelar</button></div>}
      {loading && !data ? <p className="p-6 text-sm">Carregando operação…</p> : <div className="divide-y">
        {tab === "accounts" && <><p className="px-4 pb-3 text-xs text-slate-500">Credencial registrada não comprova acesso ao provedor. Contas ligadas ao canal da empresa podem ser sincronizadas aqui.</p>{accounts.map(row => <article key={row.id} className="flex flex-wrap items-center gap-3 p-4">{checkbox(row.id, `${row.companyName}, ${row.name}`, row.source !== "tenant_channels" || !row.linked || !row.configurationComplete || row.needsReauthorization || row.status !== "active")}<div className="min-w-48 flex-1"><h2 className="font-semibold">{row.companyName}</h2><p className="text-sm">{row.name} · {row.externalAccountId}</p><p className="text-xs text-slate-500">{platformName(row.platform)} · {row.source === "tenant_channels" ? "Canal da empresa" : "Cadastro administrativo"}</p></div><div className="text-xs text-slate-500"><p>{!row.linked ? "Confirmar vínculo" : row.configurationComplete ? "Credencial registrada" : "Configuração incompleta"} · {row.needsReauthorization ? "Reconexão necessária" : row.connectionStatus}</p><p>Última sincronização: {date(row.lastSyncAt)}</p></div>{row.needsReauthorization && <button className="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-medium text-indigo-700" onClick={() => { setConnectionTarget({ tenantId: row.tenantId || "", platform: row.platform }); setShowConnections(true); document.getElementById("admin-media-connect")?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>Reconectar</button>}</article>)}{!accounts.length && <Empty />}</>}
        {tab === "campaigns" && <><p className="px-4 pb-3 text-xs text-slate-500">Relatórios salvos. Sincronize contas para atualizar. Dados com mais de 24h precisam de atualização para gerar recomendações.</p>{campaigns.map(row => <article key={row.id} className="flex flex-wrap items-center gap-3 p-4">{checkbox(row.id, `${row.companyName}, ${row.name}`, !row.linked || row.stale || !row.accountId || !row.campaignId)}<div className="min-w-48 flex-1"><h2 className="font-semibold">{row.name}</h2><p className="text-xs text-slate-500">{row.companyName} · {platformName(row.platform)} · {row.status} · {row.accountId}</p></div><div className="text-sm"><p>Gasto: {money(row.spend, row.currency)} · {row.conversions ?? "Sem dado"} {row.conversionLabel}</p><p>Verba diária: {money(row.dailyBudget, row.currency)}</p><p className="text-xs text-slate-500">{row.from} → {row.to} · {date(row.generatedAt)}</p>{row.stale && <p className="text-xs text-amber-700">Atualização necessária</p>}</div></article>)}{!campaigns.length && <div className="p-10 text-center"><h2 className="font-semibold">Nenhuma campanha disponível</h2><p className="mt-1 text-sm text-slate-500">Conecte e sincronize uma conta para acompanhar as campanhas aqui.</p><button className="mt-4 text-sm font-medium text-indigo-600" onClick={() => { setTab("accounts"); setSelected([]); setPreview(null); }}>Ver contas de anúncios</button></div>}</>}
        {tab === "drafts" && <>{drafts.map(row => <article key={row.id} className="flex gap-3 p-4">{checkbox(row.id, row.title, !row.linked || !["pending_review", "approved_pending_apply"].includes(row.status))}<div><p className="text-xs text-slate-500">{row.companyName} · {statusName(row.status)}</p><h2 className="mt-1 font-semibold">{row.title}</h2><p className="mt-1 text-sm">{row.reason}</p><p className="mt-1 text-xs text-slate-500">{row.target.campaignName || row.target.campaignId} · {row.target.adAccountId}</p>{row.change.to !== null && <p className="mt-2 text-sm">Verba: {money(row.change.from, row.change.currency)} → {money(row.change.to, row.change.currency)}</p>}<details className="mt-2 text-xs"><summary className="cursor-pointer text-indigo-700">Ver alteração proposta</summary><pre className="mt-2 max-w-full overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-50 p-3">{JSON.stringify(row.details, null, 2)}</pre></details>{!row.previewComplete && <p className="mt-2 text-xs text-amber-700">Esta alteração exige revisão completa na área da empresa.</p>}<ul className="mt-2 text-xs text-slate-500">{row.evidence.map((item, index) => <li key={index}>{item}</li>)}</ul></div></article>)}{!drafts.length && <Empty />}</>}
        {tab === "tracking" && <>{tracking.map(row => <article key={row.id} className="p-4"><h2 className="font-semibold">{row.companyName}</h2><p className="mt-1 text-sm">{row.enabled ? "Ativado" : "Desativado"} · Consentimento {row.consentMode === "required" ? "obrigatório" : "implícito"}</p><p className="mt-1 text-xs text-slate-500">{row.domains.join(", ") || "Sem domínio"} · Último evento: {row.lastEventName || "nenhum"}, {date(row.lastEventAt)}</p><Link className="mt-2 inline-block text-sm text-indigo-600" href={`/admin/clientes/${encodeURIComponent(row.clientId || row.tenantId || row.id)}`}>Abrir empresa</Link></article>)}{!tracking.length && <Empty />}</>}
        {tab === "pixels" && <div className="p-4"><details className="mb-4 rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Cadastrar pixel</summary><form onSubmit={registerPixel} className="mt-4 flex flex-wrap gap-2"><select className={field} required aria-label="Empresa do pixel" value={pixel.tenantId} onChange={event => setPixel({ ...pixel, tenantId: event.target.value })}><option value="">Empresa</option>{companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select><select className={field} aria-label="Provedor do pixel" value={pixel.provider} onChange={event => setPixel({ ...pixel, provider: event.target.value })}>{[["meta", "Meta"], ["google", "Google"], ["tiktok", "TikTok"], ["other", "Outro"]].map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>{([["name", "Nome"], ["externalId", "ID do pixel ou conversão"], ["domains", "Domínios separados por vírgula"]] as const).map(([key, label]) => <input className={field} key={key} required={key !== "domains"} placeholder={label} aria-label={label} value={pixel[key]} onChange={event => setPixel({ ...pixel, [key]: event.target.value })} />)}<button className={button} disabled={busy}>Salvar pixel</button></form></details><p className="my-3 text-xs text-slate-500">O cadastro organiza o inventário. Recebimento de eventos e acesso ao pixel precisam de verificação no provedor.</p>{pixels.map(row => <article key={row.id} className="border-t py-3"><p className="font-semibold">{row.name} · {row.companyName}</p><p className="text-xs text-slate-500">{row.provider} · {row.externalId} · {row.verificationStatus === "provider_access_verified" ? "Acesso no provedor verificado; eventos ainda não verificados" : "Recebimento de eventos não verificado"} · {row.domains.join(", ")}</p></article>)}</div>}
      </div>}
    </section>
    {!!history.length && <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Histórico de lotes</summary>{history.map(row => <div key={row.id} className="mt-3 border-t pt-3 text-sm"><p>{row.action} · {row.status} · {row.total} itens</p>{row.results.map((result, index) => <p key={index} className={`mt-1 text-xs ${result.ok ? "text-emerald-700" : "text-red-700"}`}>{result.tenantId}: {result.ok ? statusName(result.status) : result.error || "Conferir resultado no provedor"}</p>)}{row.status === "running" && <p className="mt-1 text-amber-700">Lote em execução ou interrompido. Confira os resultados antes de repetir ações.</p>}</div>)}</details>}
    {data && <p className="text-xs text-slate-500">Consulta em {date(data.generatedAt)}.</p>}
  </div>;
}
function Empty() { return <p className="p-8 text-center text-sm text-slate-500">Nenhum registro para estes filtros.</p>; }
