"use client";
import { useCallback, useEffect, useState } from "react";
import { authedFetch } from "@/app/lib/authed-fetch";
type Connection = { id: string; clientName: string; userName: string; scopes: string[]; status: string };
type Payload = { enabled: boolean; partial: boolean; endpoint: string; readiness: { ready: boolean; publicHttps: boolean; contextSecretReady: boolean; policyEnabled: boolean }; items: Connection[] };
const button = "rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40";
export default function AdminMcpPage() {
  const [data, setData] = useState<Payload | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [endpoint, setEndpoint] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { const response = await authedFetch("/api/admin/mcp/connections", { signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha na consulta."); if (!signal?.aborted) setData(payload); }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal).catch(err => { if (!controller.signal.aborted) setError(err.message); }); return () => controller.abort(); }, [load]);
  useEffect(() => { if (data?.endpoint) setEndpoint(data.endpoint); }, [data?.endpoint]);
  async function change(id?: string) { setBusy(true); setError(""); try { const response = await authedFetch("/api/admin/mcp/connections", { method: id ? "DELETE" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(id ? { id } : { enabled: !data?.enabled }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha ao salvar."); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao salvar."); } finally { setBusy(false); } }
  const nextStep = !data?.readiness.publicHttps ? "Publique a Altum em um endereço HTTPS antes de conectá-la ao ChatGPT." : !data?.readiness.policyEnabled ? "Ative o acesso abaixo para permitir a conexão." : "Copie o endereço abaixo no conector da Altum no ChatGPT. A conexão dá acesso somente às ferramentas globais da área administrativa.";
  return <div className="mx-auto max-w-5xl space-y-5 text-slate-900"><h1 className="text-2xl font-bold">Conectar a Altum ao ChatGPT</h1>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="space-y-4 rounded-xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{data?.readiness.ready ? "Pronta para conectar" : "Preparando a conexão"}</p><p className="mt-1 text-sm text-slate-500">{nextStep}</p></div><button className={button} disabled={!data || busy} onClick={() => void change()}>{data?.enabled ? "Desativar acesso" : "Ativar acesso"}</button></div><label className="block text-sm">Endereço para conectar<input className="mt-2 w-full rounded-lg border px-3 py-2 font-mono text-xs" readOnly value={endpoint} /></label><p className="text-xs text-slate-500">O ChatGPT usa somente ferramentas administrativas globais. Dados de empresas, clientes e segredos não fazem parte desta conexão.</p></section><section className="divide-y rounded-xl border bg-white"><h2 className="p-5 font-semibold">Conexões autorizadas</h2>{data?.partial && <p className="p-4 text-sm text-amber-700">Exibindo as cem conexões mais recentes.</p>}{data?.items.map(row => <article className="flex flex-wrap justify-between gap-3 p-5" key={row.id}><div><h3 className="font-semibold">{row.clientName} · {row.userName}</h3><p className="mt-1 text-sm">MCP administrativo · {row.status === "active" ? "Ativa" : row.status === "revoked" ? "Revogada" : "Expirada"}</p><p className="mt-1 text-xs text-slate-500">{row.scopes.join(", ")}</p></div><button className={button} disabled={busy || row.status === "revoked"} onClick={() => void change(row.id)}>Revogar conexão</button></article>)}{data && !data.items.length && <p className="p-5 text-sm text-slate-500">Nenhuma conexão autorizada ainda.</p>}</section></div>;
}
